{"name": "Login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error 'Invalid credentials' but got 'None'\nassert None == 'Invalid credentials'", "trace": "self = <tests.test_login.TestLogin object at 0x102e14760>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"11a37cfb11b49d2c85a0730fc8105364\")>\n\n    @allure.title(\"Login with invalid credentials\")\n    def test_login_invalid_user_details(self, driver):\n        login_page = LoginPage(driver)\n        alert_message=login_page.login_invalid_details(\"abc@gmail.com\", \"wrongpass\")\n>       assert alert_message== \"Invalid credentials\",\\\n            f\"Expected error 'Invalid credentials' but got '{alert_message}'\"\nE       AssertionError: Expected error 'Invalid credentials' but got 'None'\nE       assert None == 'Invalid credentials'\n\ntest_login.py:36: AssertionError"}, "attachments": [{"name": "test_login_invalid_user_details_2025-06-23_15-56-49.png", "source": "652785d0-b9fe-4f1a-bcd5-62c43d011ef7-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "de709d46-a906-45b5-91dd-837c23d01797-attachment.txt", "type": "text/plain"}], "start": 1750674398709, "stop": 1750674409588, "uuid": "597ea8be-2fc0-4c0f-adb1-600b6c8a34ef", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "86916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}