{"name": "Login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error 'Invalid credentials' but got 'None'\nassert None == 'Invalid credentials'", "trace": "self = <tests.test_login.TestLogin object at 0x1046c5670>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9aa081d6522694e6d69d9cd7761f984e\")>\n\n    @allure.title(\"Login with invalid credentials\")\n    def test_login_invalid_user_details(self, driver):\n        login_page = LoginPage(driver)\n        alert_message=login_page.login_invalid_details(\"abc@gmail.com\", \"wrongpass\")\n>       assert alert_message== \"Invalid credentials\",\\\n            f\"Expected error 'Invalid credentials' but got '{alert_message}'\"\nE       AssertionError: Expected error 'Invalid credentials' but got 'None'\nE       assert None == 'Invalid credentials'\n\ntest_login.py:36: AssertionError"}, "attachments": [{"name": "test_login_invalid_user_details_2025-06-23_15-58-45.png", "source": "7133e81a-ae5c-4a3c-b2b1-8413f2aaa875-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "ec9be612-e8c6-4ad4-8dbc-48e3d858ff8f-attachment.txt", "type": "text/plain"}], "start": 1750674514637, "stop": 1750674525605, "uuid": "37dcbca1-6936-4513-9a55-70017187e549", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "87023-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}