{"name": "Login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error 'Invalid credentials' but got 'None'\nassert None == 'Invalid credentials'", "trace": "self = <tests.test_login.TestLogin object at 0x1043807f0>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"93e6c2af99bd68764b347cc43d8bd89d\")>\n\n    @allure.title(\"Login with invalid credentials\")\n    def test_login_invalid_user_details(self, driver):\n        login_page = LoginPage(driver)\n        alert_message=login_page.login_invalid_details(\"abc@gmail.com\", \"wrongpass\")\n>       assert alert_message== \"Invalid credentials\",\\\n            f\"Expected error 'Invalid credentials' but got '{alert_message}'\"\nE       AssertionError: Expected error 'Invalid credentials' but got 'None'\nE       assert None == 'Invalid credentials'\n\ntest_login.py:36: AssertionError"}, "attachments": [{"name": "test_login_invalid_user_details_2025-06-23_15-52-35.png", "source": "702492fb-d5de-4c63-88d1-affb3389bc42-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "6689a797-a84c-4e61-be69-91358b8dea42-attachment.txt", "type": "text/plain"}], "start": 1750674154116, "stop": 1750674155142, "uuid": "3f2575d4-ce2a-4d40-af32-514e05d2c1ff", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "86613-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}