{"name": "Login with invalid credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Expected error 'Invalid credentials' but got 'None'\nassert None == 'Invalid credentials'", "trace": "self = <tests.test_login.TestLogin object at 0x1024b9730>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"6a573ae62d8bdfc6b4a3902a9a3d198c\")>\n\n    @allure.title(\"Login with invalid credentials\")\n    def test_login_invalid_user_details(self, driver):\n        login_page = LoginPage(driver)\n        alert_message=login_page.login_invalid_details(\"abc@gmail.com\", \"wrongpass\")\n>       assert alert_message== \"Invalid credentials\",\\\n            f\"Expected error 'Invalid credentials' but got '{alert_message}'\"\nE       AssertionError: Expected error 'Invalid credentials' but got 'None'\nE       assert None == 'Invalid credentials'\n\ntest_login.py:36: AssertionError"}, "attachments": [{"name": "test_login_invalid_user_details_2025-06-23_15-56-09.png", "source": "ab40f8ba-1a21-4f3d-b305-3a940237894b-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "1fc665e9-0347-47df-9cc0-eceee0fd0121-attachment.txt", "type": "text/plain"}], "start": 1750674358556, "stop": 1750674369299, "uuid": "be0a3289-3ff8-4ed3-b6c6-8d7f013e5a70", "historyId": "6dc9505648e45d1fa7d0d34aa44c65e4", "testCaseId": "6dc9505648e45d1fa7d0d34aa44c65e4", "fullName": "src.tests.test_login.TestLogin#test_login_invalid_user_details", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "macs-MacBook-Pro.local"}, {"name": "thread", "value": "86763-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_login"}]}