WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103613670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103613bb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103613430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10362edf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10362ebe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643340>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643c70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103643e80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103655100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036555e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036557f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103655a30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036551c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103655b80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103655dc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366a2e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366a4f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366a730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366ac10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366ae20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367b0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103613d60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367b160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367b430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367b910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367bb20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367bd60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103690280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103690490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036906d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10367b6a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10366a070>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103690a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103690f40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a4190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a43d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a48b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a4ac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a4d00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a45e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036908b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b7040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b75b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b77c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b7a00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b7ee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cb130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cb370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b7d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036b72e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cb520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cbc10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cbe20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036df0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036df580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036df790>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036df9d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036dfeb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036cb910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036dfb80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f4280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f4490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f46d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f4bb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f4dc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036f48e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1041078b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107ac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107d00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411b220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411b430>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411b670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411bb50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411bd60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104107610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411bee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412d130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412d370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412d850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412da60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412dca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413f1c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413f3d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10412deb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a4f70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413f5b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413f7c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413fca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10413feb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/element
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156820>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156be0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156b20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104156e20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416a370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416a580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416a7c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416acd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416aee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417e160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10411b8b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417e220>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417e520>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30/execute/sync
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417ea00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417ec10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10417ed90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b956b21d3615f71e54dbeeb3e99f0c30